services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=frambo_db'
      - 'POSTGRES_PASSWORD=tedpoley'
      - 'POSTGRES_USER=mattoi'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
